/*
 * Copyright (C) 2019 Jose Sanchis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package Vistas;

import Comunes.colores;
import Daos.DaoLibro;
import Pojos.Libro;
import Renders.comboBoxRender;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.border.Border;

/**
 *
 * @author Jose Sanchis
 */
public class FrameInputLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrameDevoluciones
     */
    /**
     * Modos de busqueada: - busquedaPorCodigo = true: por codigo del libro
     * (codigo de barras) - busquedaPorCodigo = false: por nombre del libro
     * (debe ser exacto)
     *
     * "Por defecto el modo de busqueda es el true, es decir, por el codigo del
     * libro"
     */
    public boolean buscquedaPorCodigo = true;

    private FrameLibro gestLibro = null;

    DaoLibro daoLibro;

    List<Libro> listaLibros;

    public FrameInputLibro() {
        initComponents();
        setModoDeBusqueda(buscquedaPorCodigo);
        this.setLocationRelativeTo(null);

        daoLibro = new DaoLibro();

        //<editor-fold defaultstate="collapsed" desc="configuracion Combobox">
        cbCurso.setUI(new comboBoxRender());
        cbCurso.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                    JList list, Object value, int index,
                    boolean isSelected, boolean hasFocus) {
                JLabel l = (JLabel) super.getListCellRendererComponent(
                        list, value, index, isSelected, hasFocus);
                if (isSelected) {
                    l.setForeground(colores.fondo);
                    l.setBackground(colores.buttons);
                } else {
                    l.setForeground(colores.buttons);
                    l.setBackground(colores.fondo);
                }
                return l;
            }
        });
//</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNew = new com.mommoo.flat.button.FlatButton();
        bodyCode = new javax.swing.JPanel();
        textTitle = new javax.swing.JLabel();
        textCodigoLibro = new javax.swing.JTextField();
        btnBuscar = new com.mommoo.flat.button.FlatButton();
        bodyListado = new javax.swing.JPanel();
        textTitle1 = new javax.swing.JLabel();
        textNombreLibro = new javax.swing.JTextField();
        cbCurso = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistResultadoLibros = new javax.swing.JList();
        botonera = new javax.swing.JPanel();
        btnCancel = new com.mommoo.flat.button.FlatButton();
        btnChangeMethod = new com.mommoo.flat.button.FlatButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devoluciones");
        setBackground(new java.awt.Color(239, 235, 233));
        setMinimumSize(new java.awt.Dimension(600, 36));
        setResizable(false);

        head.setBackground(new java.awt.Color(58, 39, 35));
        head.setPreferredSize(new java.awt.Dimension(135, 75));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión libro");

        btnNew.setBackground(new java.awt.Color(66, 47, 44));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/plus.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bodyCode.setBackground(new java.awt.Color(239, 235, 233));

        textTitle.setBackground(new java.awt.Color(51, 51, 51));
        textTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textTitle.setForeground(new java.awt.Color(51, 51, 51));
        textTitle.setText("Codigo de barras:");
        textTitle.setToolTipText("");

        textCodigoLibro.setBackground(new java.awt.Color(239, 235, 233));
        textCodigoLibro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textCodigoLibro.setForeground(new java.awt.Color(51, 51, 51));
        textCodigoLibro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textCodigoLibro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        textCodigoLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCodigoLibroKeyPressed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(66, 47, 44));
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/magnify.png"))); // NOI18N
        btnBuscar.setCornerRound(10);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyCodeLayout = new javax.swing.GroupLayout(bodyCode);
        bodyCode.setLayout(bodyCodeLayout);
        bodyCodeLayout.setHorizontalGroup(
            bodyCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyCodeLayout.createSequentialGroup()
                        .addComponent(textTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bodyCodeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textCodigoLibro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bodyCodeLayout.setVerticalGroup(
            bodyCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(textCodigoLibro))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        bodyListado.setBackground(new java.awt.Color(239, 235, 233));

        textTitle1.setBackground(new java.awt.Color(51, 51, 51));
        textTitle1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textTitle1.setForeground(new java.awt.Color(51, 51, 51));
        textTitle1.setText("Listado de libros:");
        textTitle1.setToolTipText("");

        textNombreLibro.setBackground(new java.awt.Color(239, 235, 233));
        textNombreLibro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textNombreLibro.setForeground(new java.awt.Color(102, 102, 102));
        textNombreLibro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textNombreLibro.setText("Escribe nombre del libro...");
        textNombreLibro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        textNombreLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNombreLibroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNombreLibroKeyReleased(evt);
            }
        });

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlistResultadoLibros.setBackground(new java.awt.Color(239, 235, 233));
        jlistResultadoLibros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlistResultadoLibros.setForeground(new java.awt.Color(51, 51, 51));
        jlistResultadoLibros.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlistResultadoLibros);

        javax.swing.GroupLayout bodyListadoLayout = new javax.swing.GroupLayout(bodyListado);
        bodyListado.setLayout(bodyListadoLayout);
        bodyListadoLayout.setHorizontalGroup(
            bodyListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyListadoLayout.createSequentialGroup()
                        .addComponent(textNombreLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyListadoLayout.createSequentialGroup()
                        .addComponent(textTitle1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        bodyListadoLayout.setVerticalGroup(
            bodyListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonera.setBackground(new java.awt.Color(239, 235, 233));

        btnCancel.setBackground(new java.awt.Color(66, 47, 44));
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancel.setText("Cancelar");
        btnCancel.setCornerRound(10);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setPreferredSize(new java.awt.Dimension(141, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnChangeMethod.setBackground(new java.awt.Color(66, 47, 44));
        btnChangeMethod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChangeMethod.setText("Listar libros");
        btnChangeMethod.setCornerRound(10);
        btnChangeMethod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangeMethod.setPreferredSize(new java.awt.Dimension(248, 30));
        btnChangeMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoneraLayout = new javax.swing.GroupLayout(botonera);
        botonera.setLayout(botoneraLayout);
        botoneraLayout.setHorizontalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        botoneraLayout.setVerticalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
            .addComponent(bodyCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(bodyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnChangeMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeMethodActionPerformed
        // TODO add your handling code here:
        buscquedaPorCodigo = !buscquedaPorCodigo;
        setModoDeBusqueda(buscquedaPorCodigo);
    }//GEN-LAST:event_btnChangeMethodActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Pulsación de botón de busqueda
        buscarLibroPorCodigo(textCodigoLibro.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void textNombreLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreLibroKeyReleased
        //Metodo del placeholder en la busqueda del listado
        String nombreLibro = textNombreLibro.getText();

        if (nombreLibro.length() == 0) {
            textNombreLibro.setText("Escribe nombre del libro...");
            textNombreLibro.setForeground(new Color(102, 102, 102));
        }

        filtroListaLibro(textNombreLibro.getText());
    }//GEN-LAST:event_textNombreLibroKeyReleased

    private void textNombreLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreLibroKeyPressed
        //Metodo del placeholder en la busqueda del listado
        String nombreLibro = textNombreLibro.getText();

        if (nombreLibro.length() > 0 && nombreLibro.equals("Escribe nombre del libro...")) {
            textNombreLibro.setText("");
            textNombreLibro.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_textNombreLibroKeyPressed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //Pulsación en el boton de nuevo libro
        this.setVisible(false);
        if (gestLibro == null) {
            gestLibro = new FrameLibro(buscquedaPorCodigo, null);
        }
        if (!gestLibro.isVisible()) {
            gestLibro = null;
            gestLibro = new FrameLibro(buscquedaPorCodigo, null);
        }
        gestLibro.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void textCodigoLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoLibroKeyPressed
        //Pulsacion de la tecla enter cuando el campo del codigo tiene el foco
        if (textCodigoLibro.hasFocus()) {
            textCodigoLibro.addKeyListener(new KeyAdapter() {
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                        buscarLibroPorCodigo(textCodigoLibro.getText());
                    }
                }
            });
        }
    }//GEN-LAST:event_textCodigoLibroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDevoluciones().setVisible(true);
            }
        });
    }

    public void setModoDeBusqueda(boolean modoBusqueda) {
        if (modoBusqueda) {
            bodyCode.setVisible(modoBusqueda);
            bodyListado.setVisible(!modoBusqueda);
            btnChangeMethod.setText("Listado de libros");
        } else {
            listaLibros = daoLibro.buscarTodos();

            DefaultListModel listModel = new DefaultListModel();
            for (int i = 0; i < listaLibros.size(); i++) {
                listModel.addElement(listaLibros.get(i).getNombre());
            }
            jlistResultadoLibros.setModel(listModel);

            bodyCode.setVisible(modoBusqueda);
            bodyListado.setVisible(!modoBusqueda);
            btnChangeMethod.setText("Buscar por código");
        }
        this.pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyCode;
    private javax.swing.JPanel bodyListado;
    private javax.swing.JPanel botonera;
    private com.mommoo.flat.button.FlatButton btnBuscar;
    private com.mommoo.flat.button.FlatButton btnCancel;
    private com.mommoo.flat.button.FlatButton btnChangeMethod;
    private com.mommoo.flat.button.FlatButton btnNew;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlistResultadoLibros;
    private javax.swing.JTextField textCodigoLibro;
    private javax.swing.JTextField textNombreLibro;
    private javax.swing.JLabel textTitle;
    private javax.swing.JLabel textTitle1;
    // End of variables declaration//GEN-END:variables

    private void buscarLibroPorCodigo(String codigo) {
        this.setVisible(false);
        if (gestLibro == null) {
            gestLibro = new FrameLibro(buscquedaPorCodigo, codigo);
        }
        if (!gestLibro.isVisible()) {
            gestLibro = null;
            gestLibro = new FrameLibro(buscquedaPorCodigo, codigo);
        }
        gestLibro.setVisible(true);
    }

    private void filtroListaLibro(String text) {
        List<Libro> listaFiltroLibros;
        if (text.equals("Escribe nombre del libro...")) {
            //Si el valor el por defecto
            asignarModeloToList(jlistResultadoLibros, listaLibros);
        } else {
            //Si hacemos la busqueda personalizada
            listaFiltroLibros = listaLibros.stream().filter(libro -> libro.getNombre().contains(text)).collect(Collectors.toList());
            if (listaFiltroLibros.size() > 0) {
                asignarModeloToList(jlistResultadoLibros, listaFiltroLibros);
            } else {
                DefaultListModel listModel = new DefaultListModel();
                listModel.addElement("No existen libros con este nombre");
                jlistResultadoLibros.setModel(listModel);
            }
        }
    }

    private void asignarModeloToList(JList jlist, List<Libro> lista) {
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            listModel.addElement(lista.get(i).getNombre());
        }
        jlist.setModel(listModel);
    }
}
