/*
 * Copyright (C) 2019 Jose Sanchis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package Vistas;

import Utilidades.Colores;
import Utilidades.ComprobarConexion;
import Utilidades.Configuracion;
import Utilidades.ImportarAlumnosXML;
import Utilidades.ImportarContenidoXML;
import Utilidades.ImportarCursoXML;
import Utilidades.ImportarGruposXML;
import Utilidades.ImportarMatriculasXML;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.nashorn.internal.runtime.ParserException;

/**
 *
 * @author Jose Sanchis
 */
public class FrameOpciones extends javax.swing.JFrame {

    private boolean mostrarContrasena;

    private FramePopup frameCarga = null;

    /**
     * Creates new form FrameDevoluciones
     */
    public FrameOpciones() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc="Configuracion Tabbed PAne">
        //tabbedPage.setIconAt(1, new ImageIcon(getClass().getResource("/Imagenes/icons/clipboard-arrow-down-outline.png")));
        //</editor-fold>

        this.setLocationRelativeTo(null);

        cargarConfiguracion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glossPainter1 = new org.jdesktop.swingx.painter.GlossPainter();
        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHelp = new com.mommoo.flat.button.FlatButton();
        jPanel3 = new javax.swing.JPanel();
        tabbedPage = new javax.swing.JTabbedPane();
        panelGeneral = new javax.swing.JPanel();
        panelConfiguracionBBDD = new javax.swing.JPanel();
        labelConfiguracion = new javax.swing.JLabel();
        panelIP = new javax.swing.JPanel();
        labelIP = new javax.swing.JLabel();
        textIP = new javax.swing.JTextField();
        panelPuerto = new javax.swing.JPanel();
        labelPuerto = new javax.swing.JLabel();
        textPuerto = new javax.swing.JTextField();
        panelUsuario = new javax.swing.JPanel();
        labelUsuario1 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        textContrasena = new javax.swing.JPasswordField();
        btnMostrarContrasena = new com.mommoo.flat.button.FlatButton();
        btnComprobar = new com.mommoo.flat.button.FlatButton();
        panelDevoluciones = new javax.swing.JPanel();
        panelEntregas = new javax.swing.JPanel();
        panelGestiones = new javax.swing.JPanel();
        panelImportaciones = new javax.swing.JPanel();
        panelImportCursos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textRutaCursos = new javax.swing.JTextField();
        btnSeleccionCursos = new com.mommoo.flat.button.FlatButton();
        btnImportarCursos = new com.mommoo.flat.button.FlatButton();
        panelImportGrupos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textRutaGrupos = new javax.swing.JTextField();
        btnSeleccionGrupos = new com.mommoo.flat.button.FlatButton();
        btnImportarGrupos = new com.mommoo.flat.button.FlatButton();
        panelImportAsignaturas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textRutaContenidos = new javax.swing.JTextField();
        btnSeleccionAsignaturas = new com.mommoo.flat.button.FlatButton();
        btnImportarAsignaturas = new com.mommoo.flat.button.FlatButton();
        panelImportAlumnos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textRutaAlumnos = new javax.swing.JTextField();
        btnSeleccionAlumnos = new com.mommoo.flat.button.FlatButton();
        btnImportarAlumnos = new com.mommoo.flat.button.FlatButton();
        panelImportMatriculas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textRutaMatriculas = new javax.swing.JTextField();
        btnSeleccionMatriculas = new com.mommoo.flat.button.FlatButton();
        btnImportarMatriculas = new com.mommoo.flat.button.FlatButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones");
        setMinimumSize(new java.awt.Dimension(300, 36));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(5000, 0));

        panelSuperior.setBackground(new java.awt.Color(58, 39, 35));
        panelSuperior.setPreferredSize(new java.awt.Dimension(1137, 75));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opciones");
        jLabel1.setPreferredSize(new java.awt.Dimension(122, 75));

        btnHelp.setBackground(Colores.buttons);
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/help.png"))); // NOI18N
        btnHelp.setCornerRound(10);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(Colores.accent);

        tabbedPage.setBackground(Colores.accent);
        tabbedPage.setForeground(new java.awt.Color(51, 51, 51));
        tabbedPage.setToolTipText("");
        tabbedPage.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        panelGeneral.setBackground(new java.awt.Color(239, 235, 233));

        labelConfiguracion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelConfiguracion.setText("Configuración Base de Datos");

        panelIP.setPreferredSize(new java.awt.Dimension(515, 40));

        labelIP.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelIP.setText("IP");

        javax.swing.GroupLayout panelIPLayout = new javax.swing.GroupLayout(panelIP);
        panelIP.setLayout(panelIPLayout);
        panelIPLayout.setHorizontalGroup(
            panelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIPLayout.setVerticalGroup(
            panelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textIP, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPuerto.setPreferredSize(new java.awt.Dimension(515, 40));

        labelPuerto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelPuerto.setText("Puerto");

        javax.swing.GroupLayout panelPuertoLayout = new javax.swing.GroupLayout(panelPuerto);
        panelPuerto.setLayout(panelPuertoLayout);
        panelPuertoLayout.setHorizontalGroup(
            panelPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuertoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPuertoLayout.setVerticalGroup(
            panelPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPuertoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        labelUsuario1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelUsuario1.setText("Usuario");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPassword.setPreferredSize(new java.awt.Dimension(263, 40));

        labelUsuario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelUsuario.setText("Contraseña");

        btnMostrarContrasena.setBackground(Colores.buttons);
        btnMostrarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/mostrarContrasena.png"))); // NOI18N
        btnMostrarContrasena.setCornerRound(10);

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textContrasena)
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addComponent(btnMostrarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnComprobar.setBackground(Colores.buttons);
        btnComprobar.setForeground(Colores.fondo);
        btnComprobar.setText("Comprobar");
        btnComprobar.setCornerRound(10);
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfiguracionBBDDLayout = new javax.swing.GroupLayout(panelConfiguracionBBDD);
        panelConfiguracionBBDD.setLayout(panelConfiguracionBBDDLayout);
        panelConfiguracionBBDDLayout.setHorizontalGroup(
            panelConfiguracionBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionBBDDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfiguracionBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(panelPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(panelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionBBDDLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelConfiguracionBBDDLayout.setVerticalGroup(
            panelConfiguracionBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionBBDDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConfiguracionBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConfiguracionBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        tabbedPage.addTab("General", panelGeneral);

        panelDevoluciones.setBackground(new java.awt.Color(239, 235, 233));

        javax.swing.GroupLayout panelDevolucionesLayout = new javax.swing.GroupLayout(panelDevoluciones);
        panelDevoluciones.setLayout(panelDevolucionesLayout);
        panelDevolucionesLayout.setHorizontalGroup(
            panelDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        panelDevolucionesLayout.setVerticalGroup(
            panelDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        tabbedPage.addTab("Devoluciones", panelDevoluciones);

        panelEntregas.setBackground(new java.awt.Color(239, 235, 233));

        javax.swing.GroupLayout panelEntregasLayout = new javax.swing.GroupLayout(panelEntregas);
        panelEntregas.setLayout(panelEntregasLayout);
        panelEntregasLayout.setHorizontalGroup(
            panelEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        panelEntregasLayout.setVerticalGroup(
            panelEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        tabbedPage.addTab("Entregas", panelEntregas);

        panelGestiones.setBackground(new java.awt.Color(239, 235, 233));

        javax.swing.GroupLayout panelGestionesLayout = new javax.swing.GroupLayout(panelGestiones);
        panelGestiones.setLayout(panelGestionesLayout);
        panelGestionesLayout.setHorizontalGroup(
            panelGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        panelGestionesLayout.setVerticalGroup(
            panelGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        tabbedPage.addTab("Gestiones", panelGestiones);

        panelImportaciones.setBackground(Colores.fondo);

        panelImportCursos.setBackground(Colores.fondo);
        panelImportCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Importación Cursos:");
        jLabel2.setToolTipText("");

        textRutaCursos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionCursos.setBackground(Colores.buttons);
        btnSeleccionCursos.setText("...");
        btnSeleccionCursos.setCornerRound(10);
        btnSeleccionCursos.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionCursosActionPerformed(evt);
            }
        });

        btnImportarCursos.setBackground(Colores.buttons);
        btnImportarCursos.setText("Importar");
        btnImportarCursos.setToolTipText("");
        btnImportarCursos.setCornerRound(10);
        btnImportarCursos.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportCursosLayout = new javax.swing.GroupLayout(panelImportCursos);
        panelImportCursos.setLayout(panelImportCursosLayout);
        panelImportCursosLayout.setHorizontalGroup(
            panelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportCursosLayout.createSequentialGroup()
                .addGroup(panelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImportCursosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textRutaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImportCursosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportCursosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelImportCursosLayout.setVerticalGroup(
            panelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImportGrupos.setBackground(Colores.fondo);
        panelImportGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Importación Grupos:");

        textRutaGrupos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionGrupos.setBackground(Colores.buttons);
        btnSeleccionGrupos.setText("...");
        btnSeleccionGrupos.setCornerRound(10);
        btnSeleccionGrupos.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionGruposActionPerformed(evt);
            }
        });

        btnImportarGrupos.setBackground(Colores.buttons);
        btnImportarGrupos.setText("Importar");
        btnImportarGrupos.setToolTipText("");
        btnImportarGrupos.setCornerRound(10);
        btnImportarGrupos.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportGruposLayout = new javax.swing.GroupLayout(panelImportGrupos);
        panelImportGrupos.setLayout(panelImportGruposLayout);
        panelImportGruposLayout.setHorizontalGroup(
            panelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportGruposLayout.createSequentialGroup()
                .addGroup(panelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportGruposLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImportGruposLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textRutaGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelImportGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImportGruposLayout.setVerticalGroup(
            panelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImportAsignaturas.setBackground(Colores.fondo);
        panelImportAsignaturas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Importación Asignaturas:");

        textRutaContenidos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionAsignaturas.setBackground(Colores.buttons);
        btnSeleccionAsignaturas.setText("...");
        btnSeleccionAsignaturas.setCornerRound(10);
        btnSeleccionAsignaturas.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionAsignaturasActionPerformed(evt);
            }
        });

        btnImportarAsignaturas.setBackground(Colores.buttons);
        btnImportarAsignaturas.setText("Importar");
        btnImportarAsignaturas.setToolTipText("");
        btnImportarAsignaturas.setCornerRound(10);
        btnImportarAsignaturas.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarAsignaturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportAsignaturasLayout = new javax.swing.GroupLayout(panelImportAsignaturas);
        panelImportAsignaturas.setLayout(panelImportAsignaturasLayout);
        panelImportAsignaturasLayout.setHorizontalGroup(
            panelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportAsignaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportAsignaturasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImportAsignaturasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textRutaContenidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImportAsignaturasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelImportAsignaturasLayout.setVerticalGroup(
            panelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportAsignaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(panelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaContenidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImportarAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelImportAlumnos.setBackground(Colores.fondo);
        panelImportAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Importación Alumnos:");

        textRutaAlumnos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionAlumnos.setBackground(Colores.buttons);
        btnSeleccionAlumnos.setText("...");
        btnSeleccionAlumnos.setCornerRound(10);
        btnSeleccionAlumnos.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionAlumnosActionPerformed(evt);
            }
        });

        btnImportarAlumnos.setBackground(Colores.buttons);
        btnImportarAlumnos.setText("Importar");
        btnImportarAlumnos.setToolTipText("");
        btnImportarAlumnos.setCornerRound(10);
        btnImportarAlumnos.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportAlumnosLayout = new javax.swing.GroupLayout(panelImportAlumnos);
        panelImportAlumnos.setLayout(panelImportAlumnosLayout);
        panelImportAlumnosLayout.setHorizontalGroup(
            panelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImportAlumnosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textRutaAlumnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImportAlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportAlumnosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelImportAlumnosLayout.setVerticalGroup(
            panelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImportMatriculas.setBackground(Colores.fondo);
        panelImportMatriculas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Importación Matriculas:");

        textRutaMatriculas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionMatriculas.setBackground(Colores.buttons);
        btnSeleccionMatriculas.setText("...");
        btnSeleccionMatriculas.setCornerRound(10);
        btnSeleccionMatriculas.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionMatriculasActionPerformed(evt);
            }
        });

        btnImportarMatriculas.setBackground(Colores.buttons);
        btnImportarMatriculas.setText("Importar");
        btnImportarMatriculas.setToolTipText("");
        btnImportarMatriculas.setCornerRound(10);
        btnImportarMatriculas.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarMatriculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportMatriculasLayout = new javax.swing.GroupLayout(panelImportMatriculas);
        panelImportMatriculas.setLayout(panelImportMatriculasLayout);
        panelImportMatriculasLayout.setHorizontalGroup(
            panelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportMatriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImportMatriculasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textRutaMatriculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImportMatriculasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportMatriculasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelImportMatriculasLayout.setVerticalGroup(
            panelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportMatriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImportacionesLayout = new javax.swing.GroupLayout(panelImportaciones);
        panelImportaciones.setLayout(panelImportacionesLayout);
        panelImportacionesLayout.setHorizontalGroup(
            panelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImportCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImportAsignaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImportMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImportGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImportAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelImportacionesLayout.setVerticalGroup(
            panelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImportCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImportGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImportAsignaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImportAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImportMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPage.addTab("Importaciones", panelImportaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPage)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPage, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * Controlador del botón de Ayuda
     */
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        switch (tabbedPage.getSelectedIndex()) {
            case 0:
                //Ayuda de la pestaña general (opciones)
                break;
            case 1:
                //Ayuda de la pestaña Devoluciones (opciones)
                break;
            case 2:
                //Ayuda de la pestaña Entregas (opciones)
                break;
            case 3:
                //Ayuda de la pestaña Gestiones (opciones)
                break;
            case 4:
                //Ayuda de la pestaña Importaciones (opciones)
                break;
        }
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar las matriculas
     */
    private void btnImportarMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarMatriculasActionPerformed
        // TODO add your handling code here:

        if (!textRutaMatriculas.getText().equals("")) {
            try {
                new ImportarMatriculasXML(textRutaMatriculas.getText());

                JOptionPane.showMessageDialog(this, "Matrículas importadas correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar las matrículas.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar las matrículas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarMatriculasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de las matriculas
     */
    private void btnSeleccionMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionMatriculasActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaMatriculas.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionMatriculasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar los cursos
     */
    private void btnImportarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCursosActionPerformed
        // TODO add your handling code here:
        if (!textRutaCursos.getText().equals("")) {
            try {
                new ImportarCursoXML(textRutaCursos.getText());

                JOptionPane.showMessageDialog(this, "Cursos importados correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar los cursos.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar los cursos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarCursosActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de los cursos
     */
    private void btnSeleccionCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionCursosActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaCursos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionCursosActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de los grupos
     */
    private void btnSeleccionGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionGruposActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaGrupos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionGruposActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar los grupos
     */
    private void btnImportarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarGruposActionPerformed
        // TODO add your handling code here:
        if (!textRutaGrupos.getText().equals("")) {
            try {
                new ImportarGruposXML(textRutaGrupos.getText());

                JOptionPane.showMessageDialog(this, "Grupos importados correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar los grupos.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar los grupos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarGruposActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de las asignaturas
     */
    private void btnSeleccionAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionAsignaturasActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaContenidos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionAsignaturasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar las asignaturas
     */
    private void btnImportarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarAsignaturasActionPerformed
        // TODO add your handling code here:
        if (!textRutaContenidos.getText().equals("")) {
            try {
                new ImportarContenidoXML(textRutaContenidos.getText());

                JOptionPane.showMessageDialog(this, "Asignaturas importadas correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar las asignaturas.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar las asignaturas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarAsignaturasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de los alumnos
     */
    private void btnSeleccionAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionAlumnosActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaAlumnos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionAlumnosActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar los alumnos
     */
    private void btnImportarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarAlumnosActionPerformed
        // TODO add your handling code here:
        if (!textRutaAlumnos.getText().equals("")) {
            try {
                new ImportarAlumnosXML(textRutaAlumnos.getText());

                JOptionPane.showMessageDialog(this, "Alumnos importados correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar los alumnos.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar los alumnos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarAlumnosActionPerformed

    /**
     * (Pestaña General) Botón utilizado para comprobar la conexión a la BD y
     * guardar los campos de esta en caso de conexión
     *
     * @param evt
     */
    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        String error = "";
        String ip = "", usuario = "", contrasena = "";
        int puerto = -1;

        if (textIP.getText().equals("")) {
            error += "\n- La IP no puede estar vacía.";
        } else {
            ip = textIP.getText();
        }

        if (textPuerto.getText().equals("")) {
            error += "\n- El puerto no puede estar vacío.";
        } else {
            try {
                puerto = Integer.parseInt(textPuerto.getText());
            } catch (Exception e) {
                error += "\n- El puerto debe ser un valor númerico.";
            }
        }

        if (textUsuario.getText().equals("")) {
            error += "\n- El usuario no puede estar vacío.";
        } else {
            usuario = textUsuario.getText();
        }

        contrasena = textContrasena.getText();

        if (error.equals("")) {
            try {
                ComprobarConexion.comprobarConexion(ip, puerto, "institut", usuario, contrasena);

                new FramePopup("Conexión a la base de datos correcta.",
                        new ImageIcon(getClass().getResource("/Imagenes/icons/check-black.png")),
                        "Aceptar").setVisible(true);

                Configuracion.guardarRed(ip, puerto, usuario, contrasena);
            } catch (Exception e) {
                new FramePopup("Error en la conexión, revise los parámetros introducidos.",
                        new ImageIcon(getClass().getResource("/Imagenes/icons/alert-black.png")),
                        "Aceptar").setVisible(true);
            }
        } else {
            new FramePopup("Revise los siguientes errores:" + error,
                    new ImageIcon(getClass().getResource("/Imagenes/icons/alert-black.png")),
                    "Aceptar").setVisible(true);
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mommoo.flat.button.FlatButton btnComprobar;
    private com.mommoo.flat.button.FlatButton btnHelp;
    private com.mommoo.flat.button.FlatButton btnImportarAlumnos;
    private com.mommoo.flat.button.FlatButton btnImportarAsignaturas;
    private com.mommoo.flat.button.FlatButton btnImportarCursos;
    private com.mommoo.flat.button.FlatButton btnImportarGrupos;
    private com.mommoo.flat.button.FlatButton btnImportarMatriculas;
    private com.mommoo.flat.button.FlatButton btnMostrarContrasena;
    private com.mommoo.flat.button.FlatButton btnSeleccionAlumnos;
    private com.mommoo.flat.button.FlatButton btnSeleccionAsignaturas;
    private com.mommoo.flat.button.FlatButton btnSeleccionCursos;
    private com.mommoo.flat.button.FlatButton btnSeleccionGrupos;
    private com.mommoo.flat.button.FlatButton btnSeleccionMatriculas;
    private org.jdesktop.swingx.painter.GlossPainter glossPainter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelConfiguracion;
    private javax.swing.JLabel labelIP;
    private javax.swing.JLabel labelPuerto;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JPanel panelConfiguracionBBDD;
    private javax.swing.JPanel panelDevoluciones;
    private javax.swing.JPanel panelEntregas;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelGestiones;
    private javax.swing.JPanel panelIP;
    private javax.swing.JPanel panelImportAlumnos;
    private javax.swing.JPanel panelImportAsignaturas;
    private javax.swing.JPanel panelImportCursos;
    private javax.swing.JPanel panelImportGrupos;
    private javax.swing.JPanel panelImportMatriculas;
    private javax.swing.JPanel panelImportaciones;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelPuerto;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTabbedPane tabbedPage;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textIP;
    private javax.swing.JTextField textPuerto;
    private javax.swing.JTextField textRutaAlumnos;
    private javax.swing.JTextField textRutaContenidos;
    private javax.swing.JTextField textRutaCursos;
    private javax.swing.JTextField textRutaGrupos;
    private javax.swing.JTextField textRutaMatriculas;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    private void cargarConfiguracion() {
        try {
            textIP.setText(Configuracion.getIp());
            textPuerto.setText(Configuracion.getPuerto());
            textUsuario.setText(Configuracion.getUsuario());
            textContrasena.setText(Configuracion.getPassword());
        } catch (Exception e) {
            new FramePopup("Error al cargar la configuración de red.",
                    new ImageIcon("/Imagenes/icons/alert-black.png"),
                    "Aceptar").setVisible(true);
        }

    }
}
