/*
 * Copyright (C) 2019 Jose Sanchis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package Vistas;

import Pojos.Alumno;
import Pojos.Ejemplar;
import Pojos.Historial;
import Utilidades.Colores;
import Utilidades.Estado;
import Utilidades.Imagenes.Imagenes;
import Vistas.FramePopup;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;

/**
 *
 * @author Jose Sanchis
 */
public class FrameDetallesEjemplar extends javax.swing.JFrame {

    private Ejemplar ejemplar;

    /**
     * Creates new form FrameConfirmacionEntrega
     */
    public FrameDetallesEjemplar(Ejemplar ejemplar) {
        initComponents();

        this.ejemplar = ejemplar;

        this.setLocationRelativeTo(null);

        rellenarDatosMatricula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgEstados = new javax.swing.ButtonGroup();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textCodigoEjemplar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textNombreEjemplar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textAsignaturaEjemplar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textCursoEjemplar = new javax.swing.JLabel();
        panelEjemplares = new javax.swing.JPanel();
        panelCuerpoEjemplares = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAlumnos = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        panelEstadoInicialParent = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        panelEstadoInicial = new javax.swing.JPanel();
        btnBadStatusInicial = new javax.swing.JLabel();
        btnRegularStatusInicial = new javax.swing.JLabel();
        btnGoodStatusInicial = new javax.swing.JLabel();
        panelEstadoFinalParent = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        panelEstadoFinal = new javax.swing.JPanel();
        btnBadStatusFinal = new javax.swing.JLabel();
        btnRegularStatusFinal = new javax.swing.JLabel();
        btnGoodStatusFinal = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textNombrePropietario = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        textFechaEntregaEjemplar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        textEstadoInicialEjemplar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textObservaciones = new javax.swing.JTextArea();
        panelBotonera = new javax.swing.JPanel();
        btnAceptar = new com.mommoo.flat.button.FlatButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmación");

        panelTitulo.setBackground(Colores.fondoOscuro);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(Colores.letraTitulo);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalles del Ejemplar");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCuerpo.setBackground(Colores.fondo);

        panelDatos.setBackground(Colores.fondo);
        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(Colores.letraNormal);
        jLabel5.setText("Información General:");

        jPanel2.setBackground(Colores.fondo);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(Colores.letraNormal);
        jLabel4.setText("Código de ejemplar:");

        textCodigoEjemplar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textCodigoEjemplar.setForeground(Colores.letraNormal);
        textCodigoEjemplar.setText("1000001");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textCodigoEjemplar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCodigoEjemplar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(Colores.fondo);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(Colores.letraNormal);
        jLabel7.setText("Nombre del ejemplar:");

        textNombreEjemplar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNombreEjemplar.setForeground(Colores.letraNormal);
        textNombreEjemplar.setText("El are no es lo mateix que la de ta' tia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textNombreEjemplar))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombreEjemplar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(Colores.fondo);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(Colores.letraNormal);
        jLabel8.setText("Asignatura:");

        textAsignaturaEjemplar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textAsignaturaEjemplar.setForeground(Colores.letraNormal);
        textAsignaturaEjemplar.setText("La calle es mi gimnasio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textAsignaturaEjemplar, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAsignaturaEjemplar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(Colores.fondo);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(Colores.letraNormal);
        jLabel10.setText("Curso:");

        textCursoEjemplar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textCursoEjemplar.setForeground(Colores.letraNormal);
        textCursoEjemplar.setText("4 manzanas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textCursoEjemplar))
                    .addComponent(jLabel10))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCursoEjemplar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelEjemplares.setBackground(Colores.fondo);
        panelEjemplares.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        panelCuerpoEjemplares.setBackground(Colores.fondo);

        jScrollPane1.setBorder(null);

        listAlumnos.setBackground(Colores.fondo);
        listAlumnos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        listAlumnos.setForeground(Colores.letraNormal);
        listAlumnos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listAlumnos.setSelectionBackground(Colores.accento);
        listAlumnos.setSelectionForeground(Colores.letraBotones);
        listAlumnos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listAlumnosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listAlumnos);

        jPanel1.setBackground(Colores.fondo);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        panelEstadoInicialParent.setBackground(Colores.fondo);
        panelEstadoInicialParent.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(Colores.letraNormal);
        jLabel29.setText("Estado inicial:");

        panelEstadoInicial.setBackground(Colores.fondo);
        panelEstadoInicial.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btnBadStatusInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBadStatusInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bad_disabled.png"))); // NOI18N
        panelEstadoInicial.add(btnBadStatusInicial);

        btnRegularStatusInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegularStatusInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regular_disabled.png"))); // NOI18N
        panelEstadoInicial.add(btnRegularStatusInicial);

        btnGoodStatusInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoodStatusInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/good.png"))); // NOI18N
        panelEstadoInicial.add(btnGoodStatusInicial);

        javax.swing.GroupLayout panelEstadoInicialParentLayout = new javax.swing.GroupLayout(panelEstadoInicialParent);
        panelEstadoInicialParent.setLayout(panelEstadoInicialParentLayout);
        panelEstadoInicialParentLayout.setHorizontalGroup(
            panelEstadoInicialParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoInicialParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoInicialParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadoInicialParentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelEstadoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEstadoInicialParentLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEstadoInicialParentLayout.setVerticalGroup(
            panelEstadoInicialParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoInicialParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstadoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelEstadoInicialParent);

        panelEstadoFinalParent.setBackground(Colores.fondo);
        panelEstadoFinalParent.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(Colores.letraNormal);
        jLabel30.setText("Estado final:");

        panelEstadoFinal.setBackground(Colores.fondo);
        panelEstadoFinal.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btnBadStatusFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBadStatusFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bad_disabled.png"))); // NOI18N
        panelEstadoFinal.add(btnBadStatusFinal);

        btnRegularStatusFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegularStatusFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regular_disabled.png"))); // NOI18N
        panelEstadoFinal.add(btnRegularStatusFinal);

        btnGoodStatusFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoodStatusFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/good.png"))); // NOI18N
        panelEstadoFinal.add(btnGoodStatusFinal);

        javax.swing.GroupLayout panelEstadoFinalParentLayout = new javax.swing.GroupLayout(panelEstadoFinalParent);
        panelEstadoFinalParent.setLayout(panelEstadoFinalParentLayout);
        panelEstadoFinalParentLayout.setHorizontalGroup(
            panelEstadoFinalParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoFinalParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoFinalParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadoFinalParentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelEstadoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEstadoFinalParentLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelEstadoFinalParentLayout.setVerticalGroup(
            panelEstadoFinalParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoFinalParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstadoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelEstadoFinalParent);

        javax.swing.GroupLayout panelCuerpoEjemplaresLayout = new javax.swing.GroupLayout(panelCuerpoEjemplares);
        panelCuerpoEjemplares.setLayout(panelCuerpoEjemplaresLayout);
        panelCuerpoEjemplaresLayout.setHorizontalGroup(
            panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCuerpoEjemplaresLayout.setVerticalGroup(
            panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoEjemplaresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(Colores.letraNormal);
        jLabel20.setText("Otros Alumnos que han usado este libro:");

        javax.swing.GroupLayout panelEjemplaresLayout = new javax.swing.GroupLayout(panelEjemplares);
        panelEjemplares.setLayout(panelEjemplaresLayout);
        panelEjemplaresLayout.setHorizontalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEjemplaresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEjemplaresLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelCuerpoEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEjemplaresLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEjemplaresLayout.setVerticalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEjemplaresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuerpoEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(Colores.fondo);
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(Colores.letraNormal);
        jLabel12.setText("Información prestamo:");

        jPanel7.setBackground(Colores.fondo);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(Colores.letraNormal);
        jLabel13.setText("Propietario actual:");

        textNombrePropietario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textNombrePropietario.setForeground(Colores.letraNormal);
        textNombrePropietario.setText("Jose Sanchis Belda");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textNombrePropietario))
                    .addComponent(jLabel13))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombrePropietario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(Colores.fondo);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(Colores.letraNormal);
        jLabel16.setText("Fecha de entrega:");

        textFechaEntregaEjemplar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textFechaEntregaEjemplar.setForeground(Colores.letraNormal);
        textFechaEntregaEjemplar.setText("16-11-1997 / 11:23am");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textFechaEntregaEjemplar))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFechaEntregaEjemplar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(Colores.fondo);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(Colores.letraNormal);
        jLabel18.setText("Estado inicial:");

        textEstadoInicialEjemplar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textEstadoInicialEjemplar.setForeground(Colores.letraNormal);
        textEstadoInicialEjemplar.setText("Deteriorado");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textEstadoInicialEjemplar))
                    .addComponent(jLabel18))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEstadoInicialEjemplar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textObservaciones.setEditable(false);
        textObservaciones.setBackground(Colores.fondo);
        textObservaciones.setColumns(20);
        textObservaciones.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textObservaciones.setForeground(Colores.letraNormal);
        textObservaciones.setRows(5);
        textObservaciones.setText("Sin observaciones");
        textObservaciones.setSelectedTextColor(Colores.letraBotones);
        textObservaciones.setSelectionColor(Colores.accento);
        jScrollPane2.setViewportView(textObservaciones);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCuerpoLayout = new javax.swing.GroupLayout(panelCuerpo);
        panelCuerpo.setLayout(panelCuerpoLayout);
        panelCuerpoLayout.setHorizontalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCuerpoLayout.setVerticalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotonera.setBackground(Colores.fondo);

        btnAceptar.setBackground(Colores.botones);
        btnAceptar.setForeground(Colores.letraBotones);
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/check-white.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setCornerRound(10);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBotoneraLayout = new javax.swing.GroupLayout(panelBotonera);
        panelBotonera.setLayout(panelBotoneraLayout);
        panelBotoneraLayout.setHorizontalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBotoneraLayout.setVerticalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAlumnosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listAlumnosValueChanged
        // TODO add your handling code here:
        Alumno alumno = (Alumno) listAlumnos.getSelectedValue();
        rellenarDatosAlumnos(alumno);
    }//GEN-LAST:event_listAlumnosValueChanged

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        dispose();
    }//GEN-LAST:event_btnAceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDetallesEjemplar(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mommoo.flat.button.FlatButton btnAceptar;
    private javax.swing.JLabel btnBadStatusFinal;
    private javax.swing.JLabel btnBadStatusInicial;
    private javax.swing.JLabel btnGoodStatusFinal;
    private javax.swing.JLabel btnGoodStatusInicial;
    private javax.swing.JLabel btnRegularStatusFinal;
    private javax.swing.JLabel btnRegularStatusInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listAlumnos;
    private javax.swing.JPanel panelBotonera;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelCuerpoEjemplares;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEjemplares;
    private javax.swing.JPanel panelEstadoFinal;
    private javax.swing.JPanel panelEstadoFinalParent;
    private javax.swing.JPanel panelEstadoInicial;
    private javax.swing.JPanel panelEstadoInicialParent;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.ButtonGroup rbgEstados;
    private javax.swing.JLabel textAsignaturaEjemplar;
    private javax.swing.JLabel textCodigoEjemplar;
    private javax.swing.JLabel textCursoEjemplar;
    private javax.swing.JLabel textEstadoInicialEjemplar;
    private javax.swing.JLabel textFechaEntregaEjemplar;
    private javax.swing.JLabel textNombreEjemplar;
    private javax.swing.JLabel textNombrePropietario;
    private javax.swing.JTextArea textObservaciones;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para rellenarLos Datos de la ventana
     */
    public void rellenarDatosMatricula() {
        //<editor-fold defaultstate="collapsed" desc="Información General">
        textCodigoEjemplar.setText(ejemplar.getCodigo());
        textNombreEjemplar.setText(ejemplar.getLibro().getNombre());
        textAsignaturaEjemplar.setText(ejemplar.getLibro().getContenido().getNombre_cas());
        textCursoEjemplar.setText(ejemplar.getLibro().getContenido().getCurso().getAbreviatura());
//</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Información prestamo">
        Alumno alumnoActual = null;
        Historial historialTemp = null; //Historial de este ejemplar, con el alumno encontrado
        for (int i = 0; i < ejemplar.getHistoriales().size(); i++) {
            if (ejemplar.getHistoriales().get(i).getEjemplar().getCodigo().equals(ejemplar.getCodigo())) {
                alumnoActual = ejemplar.getHistoriales().get(i).getAlumno();
                break;
            }
        }

        for (int i = 0; i < alumnoActual.getHistoriales().size(); i++) {
            if (alumnoActual.getHistoriales().get(i).getEjemplar().getCodigo().equals(ejemplar.getCodigo())) {
                historialTemp = alumnoActual.getHistoriales().get(i);
                break;
            }
        }

        if ((alumnoActual != null) && (historialTemp != null)) {
            textNombrePropietario.setText(alumnoActual.getNombre() + " " + alumnoActual.getApellido1() + " " + alumnoActual.getApellido2());
            //<editor-fold defaultstate="collapsed" desc="Estado del libro">
            switch (historialTemp.getEstado_inicial()) {
                case 0:
                    //Deteriorado
                    textEstadoInicialEjemplar.setText("Deteriorado");
                    break;
                case 1:
                    //Usado
                    textEstadoInicialEjemplar.setText("Usado");
                    break;
                case 2:
                    //Nuevo
                    textEstadoInicialEjemplar.setText("Nuevo");
                    break;
            }
//</editor-fold>
            textFechaEntregaEjemplar.setText(historialTemp.getFecha_inicial().toString());
            textObservaciones.setText(historialTemp.getObservaciones());
        }
//</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Información Alumnos">
        List<Alumno> listaAlumnos = new ArrayList<>();

        for (int i = 0; i < ejemplar.getHistoriales().size(); i++) {
            listaAlumnos.add(ejemplar.getHistoriales().get(i).getAlumno());
        }

        asignarModeloToList(listAlumnos, listaAlumnos);
        //</editor-fold>
    }

    /**
     * Metodo para asignar un modelo de datos a una JList
     */
    private void asignarModeloToList(JList jlist, List<Alumno> lista) {
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            listModel.addElement(lista.get(i));
        }
        jlist.setModel(listModel);
        jlist.setSelectedIndex(0);
    }

    /**
     * Metodo para establecer el estado del estado del ejemplar
     *
     * @param tiempoEntrega El momento del cual queremos saber el estado.
     * ('inicial', 'final')
     * @param estado El estado del ejemplar
     * @return Devuelve un booleano para saber si se ha asignado con exito
     */
    public boolean setEstado(String tiempoEntrega, int estado) {

        if (tiempoEntrega.equals("inicial")) {
            switch (estado) {
                case Estado.deteriorado:
                    //El libro se encuentra en mal estado

                    btnBadStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/bad.png")));               //Bad face
                    btnRegularStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/regular_disabled.png")));  //Regular face
                    btnGoodStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/good_disabled.png")));     //Good face
                    break;

                case Estado.usado:
                    //El libro se encuentra en mal estado

                    btnBadStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/bad_disabled.png")));     //Bad face
                    btnRegularStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/regular.png")));          //Regular face
                    btnGoodStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/good_disabled.png")));    //Good face
                    break;

                case Estado.nuevo:
                    //El libro se encuentra en mal estado

                    btnBadStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/bad_disabled.png")));     //Bad face
                    btnRegularStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/regular_disabled.png"))); //Regular face
                    btnGoodStatusInicial.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/good.png")));             //Good face
                    break;
            }
        } else if (tiempoEntrega.equals("final")) {
            switch (estado) {
                case Estado.deteriorado:
                    //El libro se encuentra en mal estado

                    btnBadStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/bad.png")));               //Bad face
                    btnRegularStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/regular_disabled.png")));  //Regular face
                    btnGoodStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/good_disabled.png")));     //Good face
                    break;

                case Estado.usado:
                    //El libro se encuentra en mal estado

                    btnBadStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/bad_disabled.png")));     //Bad face
                    btnRegularStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/regular.png")));          //Regular face
                    btnGoodStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/good_disabled.png")));    //Good face
                    break;

                case Estado.nuevo:
                    //El libro se encuentra en mal estado

                    btnBadStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/bad_disabled.png")));     //Bad face
                    btnRegularStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/regular_disabled.png"))); //Regular face
                    btnGoodStatusFinal.setIcon(new ImageIcon(
                            getClass().getResource("/Imagenes/good.png")));             //Good face
                    break;
            }
        } else {
            return false;
        }
        return true;
    }

    /**
     * Rellenar los datos dependiendo del alumno seleccioado
     *
     * @param alumno Alumno seleccionado en la lista de alumnos
     */
    private void rellenarDatosAlumnos(Alumno alumno) {
        Historial hist = null;

        for (int i = 0; i < alumno.getHistoriales().size(); i++) {
            if (alumno.getHistoriales().get(i).getAlumno().equals(alumno)) {
                hist = alumno.getHistoriales().get(i);
                break;
            }
        }
        if (hist != null) {
            boolean estadoInicial = setEstado("inicial", hist.getEstado_inicial());
            boolean estadoFinal = setEstado("final", hist.getEstado_final());

            if ((!estadoInicial) || (!estadoFinal)) {
                new FramePopup(this, "No se ha podido asignar el estado del ejemplar",
                        Imagenes.getImagen("alert-black.png"),
                        "Aceptar").setVisible(true);
            }

        }
    }
}
