/*
 * Copyright (C) 2019 Jose Sanchis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package Vistas;

import Daos.DaoCurso;
import Daos.DaoLibro;
import Daos.DaoMatricula;
import Pojos.Curso;
import Pojos.Ejemplar;
import Pojos.Libro;
import Pojos.Matricula;
import Renders.comboBoxRender;
import Utilidades.Colores;
import Utilidades.Estado;
import static Vistas.FrameEntrega.alumno;
import excepciones.BusinessException;
import java.awt.Component;
import java.time.LocalDate;
import static java.util.Collections.list;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.SwingWorker;

/**
 *
 * @author Jose Sanchis
 */
public class FrameConfirmacionEntrega extends javax.swing.JFrame {
    
    private DaoLibro daoLibro;
    private DaoCurso daoCurso;
    
    private List<Curso> listaCurso;
    private List<Ejemplar> listaEjemplares;
    
    private FramePopup framePopup;
    
    private Matricula matricula;
    private Libro libro;
    private Ejemplar ejemplar;

    /**
     * Creates new form FrameConfirmacionEntrega
     */
    public FrameConfirmacionEntrega(Matricula idMatricula) {
        initComponents();
        
        this.matricula = idMatricula;

        //daoMatricula = new DaoMatricula(Main.gestorSesiones.getSession());
        daoCurso = new DaoCurso(Main.gestorSesiones.getSession());
        
        daoLibro = new DaoLibro(Main.gestorSesiones.getSession());

        //daoLibro.buscarPorContenido(null);
        List<Libro> listaLibros = this.matricula.getContenido().getLibros();
        for (int i = 0; i < listaLibros.size(); i++) {
            if (listaLibros.get(i).getContenido().getId() == this.matricula.getContenido().getId()) {
                libro = listaLibros.get(i);
                break;
            }
        }
        
        cargarDatos();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgEstados = new javax.swing.ButtonGroup();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        panelTipoBasico = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textTipoBasico = new javax.swing.JLabel();
        panelTipoPredominante = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textTipoPredominante = new javax.swing.JLabel();
        panelAcis = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textAcis = new javax.swing.JLabel();
        panelAcisSi = new javax.swing.JPanel();
        panelFechaIniAcis = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textFechaIniAcis = new javax.swing.JLabel();
        panelFechaFinAcis = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        textFechaFinAcis = new javax.swing.JLabel();
        panelCursoAcis = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        textCursoAcis = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        panelCurso = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        textCurso = new javax.swing.JLabel();
        panelAsignatura = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textAsignatura = new javax.swing.JLabel();
        panelIdioma = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textIdioma = new javax.swing.JLabel();
        panelCursoPendiente = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        textCursoPendiente = new javax.swing.JLabel();
        panelEjemplares = new javax.swing.JPanel();
        panelTituloEjemplares = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelCuerpoEjemplares = new javax.swing.JPanel();
        panelEstadoParent15 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        panelEstado15 = new javax.swing.JPanel();
        btnBadStatus = new javax.swing.JLabel();
        btnRegularStatus = new javax.swing.JLabel();
        btnGoodStatus = new javax.swing.JLabel();
        panelCodigoEjemplar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        flatButton3 = new com.mommoo.flat.button.FlatButton();
        panelListaEjemplres = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEjemplares = new javax.swing.JList();
        rbTodos = new javax.swing.JRadioButton();
        rbNuevos = new javax.swing.JRadioButton();
        rbUsados = new javax.swing.JRadioButton();
        panelBotonera = new javax.swing.JPanel();
        btnCancel = new com.mommoo.flat.button.FlatButton();
        flatButton1 = new com.mommoo.flat.button.FlatButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmación");

        panelTitulo.setBackground(Colores.accent);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(Colores.fondo);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar Entrega");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCuerpo.setBackground(Colores.fondo);

        panelDatos.setBackground(Colores.fondo);
        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        panelTipoBasico.setBackground(Colores.fondo);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo Básico:");

        textTipoBasico.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textTipoBasico.setText("123874534");

        javax.swing.GroupLayout panelTipoBasicoLayout = new javax.swing.GroupLayout(panelTipoBasico);
        panelTipoBasico.setLayout(panelTipoBasicoLayout);
        panelTipoBasicoLayout.setHorizontalGroup(
            panelTipoBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoBasicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoBasicoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textTipoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoBasicoLayout.setVerticalGroup(
            panelTipoBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoBasicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTipoBasico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTipoPredominante.setBackground(Colores.fondo);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Tipo Predominante:");

        textTipoPredominante.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textTipoPredominante.setText("123874534");

        javax.swing.GroupLayout panelTipoPredominanteLayout = new javax.swing.GroupLayout(panelTipoPredominante);
        panelTipoPredominante.setLayout(panelTipoPredominanteLayout);
        panelTipoPredominanteLayout.setHorizontalGroup(
            panelTipoPredominanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPredominanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoPredominanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoPredominanteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textTipoPredominante, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoPredominanteLayout.setVerticalGroup(
            panelTipoPredominanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPredominanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTipoPredominante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAcis.setBackground(Colores.fondo);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Acis:");

        textAcis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textAcis.setText("No");

        javax.swing.GroupLayout panelAcisLayout = new javax.swing.GroupLayout(panelAcis);
        panelAcis.setLayout(panelAcisLayout);
        panelAcisLayout.setHorizontalGroup(
            panelAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAcisLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textAcis))
                    .addComponent(jLabel10))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelAcisLayout.setVerticalGroup(
            panelAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAcis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAcisSi.setLayout(new java.awt.GridLayout(1, 0));

        panelFechaIniAcis.setBackground(Colores.fondo);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Fecha Inicio Acis:");

        textFechaIniAcis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textFechaIniAcis.setText("01/01/1970");

        javax.swing.GroupLayout panelFechaIniAcisLayout = new javax.swing.GroupLayout(panelFechaIniAcis);
        panelFechaIniAcis.setLayout(panelFechaIniAcisLayout);
        panelFechaIniAcisLayout.setHorizontalGroup(
            panelFechaIniAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaIniAcisLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFechaIniAcisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFechaIniAcis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaIniAcisLayout.setVerticalGroup(
            panelFechaIniAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaIniAcisLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFechaIniAcis))
        );

        panelAcisSi.add(panelFechaIniAcis);

        panelFechaFinAcis.setBackground(Colores.fondo);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Fecha Fin Acis:");

        textFechaFinAcis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textFechaFinAcis.setText("01/01/1970");

        javax.swing.GroupLayout panelFechaFinAcisLayout = new javax.swing.GroupLayout(panelFechaFinAcis);
        panelFechaFinAcis.setLayout(panelFechaFinAcisLayout);
        panelFechaFinAcisLayout.setHorizontalGroup(
            panelFechaFinAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaFinAcisLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFechaFinAcisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFechaFinAcis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaFinAcisLayout.setVerticalGroup(
            panelFechaFinAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaFinAcisLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFechaFinAcis))
        );

        panelAcisSi.add(panelFechaFinAcis);

        panelCursoAcis.setBackground(Colores.fondo);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Curso Acis:");

        textCursoAcis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textCursoAcis.setText("125452332");

        javax.swing.GroupLayout panelCursoAcisLayout = new javax.swing.GroupLayout(panelCursoAcis);
        panelCursoAcis.setLayout(panelCursoAcisLayout);
        panelCursoAcisLayout.setHorizontalGroup(
            panelCursoAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoAcisLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCursoAcisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textCursoAcis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCursoAcisLayout.setVerticalGroup(
            panelCursoAcisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoAcisLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCursoAcis))
        );

        panelAcisSi.add(panelCursoAcis);

        panelSuperior.setBackground(Colores.fondo);
        panelSuperior.setLayout(new java.awt.GridLayout(1, 4));

        panelCurso.setBackground(Colores.fondo);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Curso:");

        textCurso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textCurso.setText("1ESO");

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCursoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCurso)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelSuperior.add(panelCurso);

        panelAsignatura.setBackground(Colores.fondo);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(Colores.accent);
        jLabel2.setText("Asignatura:");

        textAsignatura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textAsignatura.setForeground(Colores.accent);
        textAsignatura.setText("Matematicas");
        textAsignatura.setMaximumSize(new java.awt.Dimension(195, 24));

        javax.swing.GroupLayout panelAsignaturaLayout = new javax.swing.GroupLayout(panelAsignatura);
        panelAsignatura.setLayout(panelAsignaturaLayout);
        panelAsignaturaLayout.setHorizontalGroup(
            panelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsignaturaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAsignaturaLayout.setVerticalGroup(
            panelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSuperior.add(panelAsignatura);

        panelIdioma.setBackground(Colores.fondo);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Idioma:");

        textIdioma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textIdioma.setText("Por defecto");

        javax.swing.GroupLayout panelIdiomaLayout = new javax.swing.GroupLayout(panelIdioma);
        panelIdioma.setLayout(panelIdiomaLayout);
        panelIdiomaLayout.setHorizontalGroup(
            panelIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdiomaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdiomaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textIdioma))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIdiomaLayout.setVerticalGroup(
            panelIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdiomaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIdioma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSuperior.add(panelIdioma);

        panelCursoPendiente.setBackground(Colores.fondo);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Curso Pendiente:");

        textCursoPendiente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textCursoPendiente.setText("12783534");

        javax.swing.GroupLayout panelCursoPendienteLayout = new javax.swing.GroupLayout(panelCursoPendiente);
        panelCursoPendiente.setLayout(panelCursoPendienteLayout);
        panelCursoPendienteLayout.setHorizontalGroup(
            panelCursoPendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoPendienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoPendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCursoPendienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textCursoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCursoPendienteLayout.setVerticalGroup(
            panelCursoPendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoPendienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCursoPendiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSuperior.add(panelCursoPendiente);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(panelAcis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAcisSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(panelTipoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTipoPredominante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAcis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAcisSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTipoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTipoPredominante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEjemplares.setBackground(Colores.fondo);
        panelEjemplares.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        panelTituloEjemplares.setBackground(Colores.fondo);
        panelTituloEjemplares.setForeground(Colores.accent);
        panelTituloEjemplares.setMinimumSize(new java.awt.Dimension(252, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(Colores.accent);
        jLabel3.setText("Ejemplares");

        javax.swing.GroupLayout panelTituloEjemplaresLayout = new javax.swing.GroupLayout(panelTituloEjemplares);
        panelTituloEjemplares.setLayout(panelTituloEjemplaresLayout);
        panelTituloEjemplaresLayout.setHorizontalGroup(
            panelTituloEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(699, Short.MAX_VALUE))
        );
        panelTituloEjemplaresLayout.setVerticalGroup(
            panelTituloEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuerpoEjemplares.setBackground(Colores.fondo);

        panelEstadoParent15.setBackground(new java.awt.Color(239, 235, 233));
        panelEstadoParent15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Estado:");

        panelEstado15.setBackground(new java.awt.Color(239, 235, 233));
        panelEstado15.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btnBadStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBadStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bad_disabled.png"))); // NOI18N
        panelEstado15.add(btnBadStatus);

        btnRegularStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegularStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regular_disabled.png"))); // NOI18N
        panelEstado15.add(btnRegularStatus);

        btnGoodStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoodStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/good.png"))); // NOI18N
        panelEstado15.add(btnGoodStatus);

        javax.swing.GroupLayout panelEstadoParent15Layout = new javax.swing.GroupLayout(panelEstadoParent15);
        panelEstadoParent15.setLayout(panelEstadoParent15Layout);
        panelEstadoParent15Layout.setHorizontalGroup(
            panelEstadoParent15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoParent15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoParent15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadoParent15Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelEstado15, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                    .addGroup(panelEstadoParent15Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEstadoParent15Layout.setVerticalGroup(
            panelEstadoParent15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoParent15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstado15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panelCodigoEjemplar.setBackground(new java.awt.Color(239, 235, 233));
        panelCodigoEjemplar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setBackground(Colores.accent);
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Codigo del libro:");

        jLabel17.setToolTipText("");

        flatButton3.setBackground(Colores.buttons);
        flatButton3.setText("Imprimir etiqueta");
        flatButton3.setCornerRound(10);
        flatButton3.setPreferredSize(new java.awt.Dimension(169, 32));

        javax.swing.GroupLayout panelCodigoEjemplarLayout = new javax.swing.GroupLayout(panelCodigoEjemplar);
        panelCodigoEjemplar.setLayout(panelCodigoEjemplarLayout);
        panelCodigoEjemplarLayout.setHorizontalGroup(
            panelCodigoEjemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodigoEjemplarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodigoEjemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCodigoEjemplarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCodigoEjemplarLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCodigoEjemplarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(flatButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCodigoEjemplarLayout.setVerticalGroup(
            panelCodigoEjemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodigoEjemplarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(flatButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelListaEjemplres.setBackground(Colores.fondo);
        panelListaEjemplres.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane1.setBorder(null);

        listEjemplares.setBackground(Colores.fondo);
        listEjemplares.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        listEjemplares.setForeground(Colores.accent);
        listEjemplares.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEjemplares.setSelectionBackground(Colores.accent);
        listEjemplares.setSelectionForeground(Colores.fondo);
        listEjemplares.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEjemplaresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEjemplares);

        rbgEstados.add(rbTodos);
        rbTodos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbTodos.setForeground(Colores.accent);
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        rbgEstados.add(rbNuevos);
        rbNuevos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbNuevos.setForeground(Colores.accent);
        rbNuevos.setText("Nuevos");
        rbNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNuevosActionPerformed(evt);
            }
        });

        rbgEstados.add(rbUsados);
        rbUsados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbUsados.setForeground(Colores.accent);
        rbUsados.setText("Usados");
        rbUsados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUsadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListaEjemplresLayout = new javax.swing.GroupLayout(panelListaEjemplres);
        panelListaEjemplres.setLayout(panelListaEjemplresLayout);
        panelListaEjemplresLayout.setHorizontalGroup(
            panelListaEjemplresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaEjemplresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaEjemplresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelListaEjemplresLayout.createSequentialGroup()
                        .addComponent(rbTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNuevos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbUsados)))
                .addContainerGap())
        );
        panelListaEjemplresLayout.setVerticalGroup(
            panelListaEjemplresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaEjemplresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelListaEjemplresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTodos)
                    .addComponent(rbNuevos)
                    .addComponent(rbUsados))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCuerpoEjemplaresLayout = new javax.swing.GroupLayout(panelCuerpoEjemplares);
        panelCuerpoEjemplares.setLayout(panelCuerpoEjemplaresLayout);
        panelCuerpoEjemplaresLayout.setHorizontalGroup(
            panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListaEjemplres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCodigoEjemplar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEstadoParent15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCuerpoEjemplaresLayout.setVerticalGroup(
            panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuerpoEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelListaEjemplres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCuerpoEjemplaresLayout.createSequentialGroup()
                        .addComponent(panelCodigoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEstadoParent15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEjemplaresLayout = new javax.swing.GroupLayout(panelEjemplares);
        panelEjemplares.setLayout(panelEjemplaresLayout);
        panelEjemplaresLayout.setHorizontalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEjemplaresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelCuerpoEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTituloEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelEjemplaresLayout.setVerticalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEjemplaresLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(panelTituloEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelCuerpoEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );

        javax.swing.GroupLayout panelCuerpoLayout = new javax.swing.GroupLayout(panelCuerpo);
        panelCuerpo.setLayout(panelCuerpoLayout);
        panelCuerpoLayout.setHorizontalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCuerpoLayout.setVerticalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBotonera.setBackground(Colores.fondo);

        btnCancel.setBackground(Colores.buttons);
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/close.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setCornerRound(10);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        flatButton1.setBackground(Colores.buttons);
        flatButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/check.png"))); // NOI18N
        flatButton1.setText("Aceptar");
        flatButton1.setCornerRound(10);

        javax.swing.GroupLayout panelBotoneraLayout = new javax.swing.GroupLayout(panelBotonera);
        panelBotonera.setLayout(panelBotoneraLayout);
        panelBotoneraLayout.setHorizontalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flatButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBotoneraLayout.setVerticalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flatButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        asignarModeloToList(listEjemplares, listaEjemplares);
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNuevosActionPerformed
        // TODO add your handling code here:
        getEjemplaresFiltrados(Estado.nuevo);
    }//GEN-LAST:event_rbNuevosActionPerformed

    private void rbUsadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUsadosActionPerformed
        getEjemplaresFiltrados(Estado.usado);
    }//GEN-LAST:event_rbUsadosActionPerformed

    private void listEjemplaresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEjemplaresValueChanged
        // TODO add your handling code here:
        ejemplar = (Ejemplar)listEjemplares.getSelectedValue();
        rellenarEjemplar();
    }//GEN-LAST:event_listEjemplaresValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameConfirmacionEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameConfirmacionEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameConfirmacionEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameConfirmacionEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameConfirmacionEntrega(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBadStatus;
    private com.mommoo.flat.button.FlatButton btnCancel;
    private javax.swing.JLabel btnGoodStatus;
    private javax.swing.JLabel btnRegularStatus;
    private com.mommoo.flat.button.FlatButton flatButton1;
    private com.mommoo.flat.button.FlatButton flatButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listEjemplares;
    private javax.swing.JPanel panelAcis;
    private javax.swing.JPanel panelAcisSi;
    private javax.swing.JPanel panelAsignatura;
    private javax.swing.JPanel panelBotonera;
    private javax.swing.JPanel panelCodigoEjemplar;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelCuerpoEjemplares;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JPanel panelCursoAcis;
    private javax.swing.JPanel panelCursoPendiente;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEjemplares;
    private javax.swing.JPanel panelEstado15;
    private javax.swing.JPanel panelEstadoParent15;
    private javax.swing.JPanel panelFechaFinAcis;
    private javax.swing.JPanel panelFechaIniAcis;
    private javax.swing.JPanel panelIdioma;
    private javax.swing.JPanel panelListaEjemplres;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTipoBasico;
    private javax.swing.JPanel panelTipoPredominante;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTituloEjemplares;
    private javax.swing.JRadioButton rbNuevos;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JRadioButton rbUsados;
    private javax.swing.ButtonGroup rbgEstados;
    private javax.swing.JLabel textAcis;
    private javax.swing.JLabel textAsignatura;
    private javax.swing.JLabel textCurso;
    private javax.swing.JLabel textCursoAcis;
    private javax.swing.JLabel textCursoPendiente;
    private javax.swing.JLabel textFechaFinAcis;
    private javax.swing.JLabel textFechaIniAcis;
    private javax.swing.JLabel textIdioma;
    private javax.swing.JLabel textTipoBasico;
    private javax.swing.JLabel textTipoPredominante;
    // End of variables declaration//GEN-END:variables

    public void rellenarDatosMatricula() {
        //<editor-fold defaultstate="collapsed" desc="Datos Matriculas">
        //Curso
        textCurso.setText(this.matricula.getCurso());

        //Asignatura
        textAsignatura.setText(this.matricula.getContenido().getNombre_cas());
        textAsignatura.setToolTipText(this.matricula.getContenido().getNombre_cas());

        //Idioma
        if (this.matricula.getIdioma().equals(" ")) {
            textIdioma.setText("Por defecto");
        } else {
            textIdioma.setText(this.matricula.getIdioma());
        }

        //Curso Pendiente
        if (this.matricula.getCurso_pendiente().equals(" ")) {
            panelCursoPendiente.setVisible(false);
        } else {
            textCursoPendiente.setText(getCursoName(this.matricula.getCurso_pendiente()).getAbreviatura());
        }

        //Acis
        if (this.matricula.getAcis().toUpperCase().equals("N")) {
            textAcis.setText("No");
            panelAcisSi.setVisible(false);
        } else {
            textAcis.setText("Si");
            textFechaIniAcis.setText(this.matricula.getFec_ini_acis() + "");
            textFechaFinAcis.setText(this.matricula.getFec_fin_acis() + "");
            textCursoAcis.setText(getCursoName(this.matricula.getCur_ref_acis()).getAbreviatura());
        }

        //Tipo básico
        if (this.matricula.getTipo_basico().equals("N")) {
            panelTipoBasico.setVisible(false);
        } else {
            textTipoBasico.setText("Pendiente");
        }

        //Tipo Predominante
        if (this.matricula.getTipo_predom().equals("I")) {
            textTipoPredominante.setText("Incompatible");
        } else {
            panelTipoPredominante.setVisible(false);
        }
//</editor-fold>
        //<editor-fold defaultstate="collapsed" desc="Datos Ejemplares">
        if (listaEjemplares.size() > 0) {
            asignarModeloToList(listEjemplares, listaEjemplares);
        }
//</editor-fold>
    }

    /**
     * Filtrado de ejemplares.
     */
    private void getEjemplaresFiltrados(int estado) {
        List<Ejemplar> listaEjemplaresTemp = listaEjemplares.
                stream().filter(ejemplar -> ejemplar.getEstado() == estado).collect(Collectors.toList());
        asignarModeloToList(listEjemplares, listaEjemplaresTemp);
    }

    /**
     * Metodo para asignar un modelo de datos a una JList
     */
    private void asignarModeloToList(JList jlist, List<Ejemplar> lista) {
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            listModel.addElement(lista.get(i));
        }
        jlist.setModel(listModel);
    }
    
    private Curso getCursoName(String cursoABuscar) {
        return listaCurso.stream().filter(curso -> curso.getCodigo().equals(cursoABuscar)).collect(Collectors.toList()).get(0);
    }
    
    private void cargarDatos() {
        SwingWorker<?, ?> worker = new SwingWorker<Void, Void>() {
            protected Void doInBackground() throws InterruptedException {
                listaCurso = daoCurso.buscarTodos();
                return null;
            }
            
            protected void done() {
                System.out.println(matricula);
                if (libro != null) {
                    listaEjemplares = libro.getEjemplares();
                }
                rellenarDatosMatricula();
                pack();
                framePopup.dispose();
            }
        };
        worker.execute();
        if (framePopup == null) {
            framePopup = new FramePopup();
        }
        framePopup.setVisible(true);
    }

    private void rellenarEjemplar() {
        setEstado(ejemplar.getEstado());
    }
    
    public void setEstado(int estado) {

        switch (estado) {
            case Estado.deteriorado:
                //El libro se encuentra en mal estado

                btnBadStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/bad.png")));               //Bad face
                btnRegularStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/regular_disabled.png")));  //Regular face
                btnGoodStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/good_disabled.png")));     //Good face
                break;

            case Estado.usado:
                //El libro se encuentra en mal estado

                btnBadStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/bad_disabled.png")));     //Bad face
                btnRegularStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/regular.png")));          //Regular face
                btnGoodStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/good_disabled.png")));    //Good face
                break;

            case Estado.nuevo:
                //El libro se encuentra en mal estado

                btnBadStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/bad_disabled.png")));     //Bad face
                btnRegularStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/regular_disabled.png"))); //Regular face
                btnGoodStatus.setIcon(new ImageIcon(
                        getClass().getResource("/Imagenes/good.png")));             //Good face
                break;
        }
    }
}
