/*
 * Copyright (C) 2019 Jose Sanchis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package Vistas;

import Utilidades.Colores;
import Utilidades.ComprobarConexion;
import Utilidades.ImportarAlumnosXML;
import Utilidades.ImportarContenidoXML;
import Utilidades.ImportarCursoXML;
import Utilidades.ImportarGruposXML;
import Utilidades.ImportarMatriculasXML;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.nashorn.internal.runtime.ParserException;

/**
 *
 * @author Jose Sanchis
 */
public class FrameOpciones extends javax.swing.JFrame {

    /**
     * Creates new form FrameDevoluciones
     */
    public FrameOpciones() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc="Configuracion Tabbed PAne">
        //tabbedPage.setIconAt(1, new ImageIcon(getClass().getResource("/Imagenes/icons/clipboard-arrow-down-outline.png")));
        //</editor-fold>

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glossPainter1 = new org.jdesktop.swingx.painter.GlossPainter();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHelp = new com.mommoo.flat.button.FlatButton();
        jPanel3 = new javax.swing.JPanel();
        tabbedPage = new javax.swing.JTabbedPane();
        PanelGeneral = new javax.swing.JPanel();
        PanelConfiguracionRed = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textIPServidor = new javax.swing.JTextField();
        btnComprobarRed = new com.mommoo.flat.button.FlatButton();
        jLabel8 = new javax.swing.JLabel();
        textPuertoServidor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PanelDevoluciones = new javax.swing.JPanel();
        PanelEntregas = new javax.swing.JPanel();
        PanelGestiones = new javax.swing.JPanel();
        PanelImportaciones = new javax.swing.JPanel();
        PanelImportCursos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textRutaCursos = new javax.swing.JTextField();
        btnSeleccionCursos = new com.mommoo.flat.button.FlatButton();
        btnImportarCursos = new com.mommoo.flat.button.FlatButton();
        PanelImportGrupos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textRutaGrupos = new javax.swing.JTextField();
        btnSeleccionGrupos = new com.mommoo.flat.button.FlatButton();
        btnImportarGrupos = new com.mommoo.flat.button.FlatButton();
        PanelImportAsignaturas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textRutaContenidos = new javax.swing.JTextField();
        btnSeleccionAsignaturas = new com.mommoo.flat.button.FlatButton();
        btnImportarAsignaturas = new com.mommoo.flat.button.FlatButton();
        PanelImportAlumnos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textRutaAlumnos = new javax.swing.JTextField();
        btnSeleccionAlumnos = new com.mommoo.flat.button.FlatButton();
        btnImportarAlumnos = new com.mommoo.flat.button.FlatButton();
        PanelImportMatriculas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textRutaMatriculas = new javax.swing.JTextField();
        btnSeleccionMatriculas = new com.mommoo.flat.button.FlatButton();
        btnImportarMatriculas = new com.mommoo.flat.button.FlatButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones");
        setMinimumSize(new java.awt.Dimension(600, 36));

        jPanel1.setBackground(new java.awt.Color(58, 39, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(1137, 75));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opciones");
        jLabel1.setPreferredSize(new java.awt.Dimension(122, 75));

        btnHelp.setBackground(Colores.buttons);
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/help.png"))); // NOI18N
        btnHelp.setCornerRound(10);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(Colores.accent);

        tabbedPage.setBackground(Colores.accent);
        tabbedPage.setForeground(new java.awt.Color(51, 51, 51));
        tabbedPage.setToolTipText("");
        tabbedPage.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        PanelGeneral.setBackground(new java.awt.Color(239, 235, 233));

        PanelConfiguracionRed.setBackground(Colores.fondo);
        PanelConfiguracionRed.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Configuración Servidor BD");
        jLabel7.setToolTipText("");

        textIPServidor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnComprobarRed.setBackground(Colores.buttons);
        btnComprobarRed.setText("Comprobar");
        btnComprobarRed.setToolTipText("");
        btnComprobarRed.setCornerRound(10);
        btnComprobarRed.setPreferredSize(new java.awt.Dimension(111, 32));
        btnComprobarRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarRedActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("IP");
        jLabel8.setToolTipText("");

        textPuertoServidor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("Puerto");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout PanelConfiguracionRedLayout = new javax.swing.GroupLayout(PanelConfiguracionRed);
        PanelConfiguracionRed.setLayout(PanelConfiguracionRedLayout);
        PanelConfiguracionRedLayout.setHorizontalGroup(
            PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfiguracionRedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConfiguracionRedLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConfiguracionRedLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConfiguracionRedLayout.createSequentialGroup()
                                .addGroup(PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textPuertoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnComprobarRed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PanelConfiguracionRedLayout.setVerticalGroup(
            PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfiguracionRedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConfiguracionRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPuertoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnComprobarRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelConfiguracionRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(544, 544, 544))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelConfiguracionRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        tabbedPage.addTab("General", PanelGeneral);

        PanelDevoluciones.setBackground(new java.awt.Color(239, 235, 233));

        javax.swing.GroupLayout PanelDevolucionesLayout = new javax.swing.GroupLayout(PanelDevoluciones);
        PanelDevoluciones.setLayout(PanelDevolucionesLayout);
        PanelDevolucionesLayout.setHorizontalGroup(
            PanelDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        PanelDevolucionesLayout.setVerticalGroup(
            PanelDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        tabbedPage.addTab("Devoluciones", PanelDevoluciones);

        PanelEntregas.setBackground(new java.awt.Color(239, 235, 233));

        javax.swing.GroupLayout PanelEntregasLayout = new javax.swing.GroupLayout(PanelEntregas);
        PanelEntregas.setLayout(PanelEntregasLayout);
        PanelEntregasLayout.setHorizontalGroup(
            PanelEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        PanelEntregasLayout.setVerticalGroup(
            PanelEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        tabbedPage.addTab("Entregas", PanelEntregas);

        PanelGestiones.setBackground(new java.awt.Color(239, 235, 233));

        javax.swing.GroupLayout PanelGestionesLayout = new javax.swing.GroupLayout(PanelGestiones);
        PanelGestiones.setLayout(PanelGestionesLayout);
        PanelGestionesLayout.setHorizontalGroup(
            PanelGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        PanelGestionesLayout.setVerticalGroup(
            PanelGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        tabbedPage.addTab("Gestiones", PanelGestiones);

        PanelImportaciones.setBackground(Colores.fondo);

        PanelImportCursos.setBackground(Colores.fondo);
        PanelImportCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Importación Cursos:");
        jLabel2.setToolTipText("");

        textRutaCursos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionCursos.setBackground(Colores.buttons);
        btnSeleccionCursos.setText("...");
        btnSeleccionCursos.setCornerRound(10);
        btnSeleccionCursos.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionCursosActionPerformed(evt);
            }
        });

        btnImportarCursos.setBackground(Colores.buttons);
        btnImportarCursos.setText("Importar");
        btnImportarCursos.setToolTipText("");
        btnImportarCursos.setCornerRound(10);
        btnImportarCursos.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelImportCursosLayout = new javax.swing.GroupLayout(PanelImportCursos);
        PanelImportCursos.setLayout(PanelImportCursosLayout);
        PanelImportCursosLayout.setHorizontalGroup(
            PanelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportCursosLayout.createSequentialGroup()
                .addGroup(PanelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelImportCursosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textRutaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImportCursosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImportCursosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelImportCursosLayout.setVerticalGroup(
            PanelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelImportCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelImportGrupos.setBackground(Colores.fondo);
        PanelImportGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Importación Grupos:");

        textRutaGrupos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionGrupos.setBackground(Colores.buttons);
        btnSeleccionGrupos.setText("...");
        btnSeleccionGrupos.setCornerRound(10);
        btnSeleccionGrupos.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionGruposActionPerformed(evt);
            }
        });

        btnImportarGrupos.setBackground(Colores.buttons);
        btnImportarGrupos.setText("Importar");
        btnImportarGrupos.setToolTipText("");
        btnImportarGrupos.setCornerRound(10);
        btnImportarGrupos.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelImportGruposLayout = new javax.swing.GroupLayout(PanelImportGrupos);
        PanelImportGrupos.setLayout(PanelImportGruposLayout);
        PanelImportGruposLayout.setHorizontalGroup(
            PanelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportGruposLayout.createSequentialGroup()
                .addGroup(PanelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImportGruposLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImportGruposLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textRutaGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(PanelImportGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelImportGruposLayout.setVerticalGroup(
            PanelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelImportGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelImportAsignaturas.setBackground(Colores.fondo);
        PanelImportAsignaturas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Importación Asignaturas:");

        textRutaContenidos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionAsignaturas.setBackground(Colores.buttons);
        btnSeleccionAsignaturas.setText("...");
        btnSeleccionAsignaturas.setCornerRound(10);
        btnSeleccionAsignaturas.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionAsignaturasActionPerformed(evt);
            }
        });

        btnImportarAsignaturas.setBackground(Colores.buttons);
        btnImportarAsignaturas.setText("Importar");
        btnImportarAsignaturas.setToolTipText("");
        btnImportarAsignaturas.setCornerRound(10);
        btnImportarAsignaturas.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarAsignaturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelImportAsignaturasLayout = new javax.swing.GroupLayout(PanelImportAsignaturas);
        PanelImportAsignaturas.setLayout(PanelImportAsignaturasLayout);
        PanelImportAsignaturasLayout.setHorizontalGroup(
            PanelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportAsignaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImportAsignaturasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImportAsignaturasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textRutaContenidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImportAsignaturasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelImportAsignaturasLayout.setVerticalGroup(
            PanelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportAsignaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(PanelImportAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaContenidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImportarAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelImportAlumnos.setBackground(Colores.fondo);
        PanelImportAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Importación Alumnos:");

        textRutaAlumnos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionAlumnos.setBackground(Colores.buttons);
        btnSeleccionAlumnos.setText("...");
        btnSeleccionAlumnos.setCornerRound(10);
        btnSeleccionAlumnos.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionAlumnosActionPerformed(evt);
            }
        });

        btnImportarAlumnos.setBackground(Colores.buttons);
        btnImportarAlumnos.setText("Importar");
        btnImportarAlumnos.setToolTipText("");
        btnImportarAlumnos.setCornerRound(10);
        btnImportarAlumnos.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelImportAlumnosLayout = new javax.swing.GroupLayout(PanelImportAlumnos);
        PanelImportAlumnos.setLayout(PanelImportAlumnosLayout);
        PanelImportAlumnosLayout.setHorizontalGroup(
            PanelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelImportAlumnosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textRutaAlumnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImportAlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImportAlumnosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelImportAlumnosLayout.setVerticalGroup(
            PanelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelImportAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelImportMatriculas.setBackground(Colores.fondo);
        PanelImportMatriculas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Importación Matriculas:");

        textRutaMatriculas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSeleccionMatriculas.setBackground(Colores.buttons);
        btnSeleccionMatriculas.setText("...");
        btnSeleccionMatriculas.setCornerRound(10);
        btnSeleccionMatriculas.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSeleccionMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionMatriculasActionPerformed(evt);
            }
        });

        btnImportarMatriculas.setBackground(Colores.buttons);
        btnImportarMatriculas.setText("Importar");
        btnImportarMatriculas.setToolTipText("");
        btnImportarMatriculas.setCornerRound(10);
        btnImportarMatriculas.setPreferredSize(new java.awt.Dimension(111, 32));
        btnImportarMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarMatriculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelImportMatriculasLayout = new javax.swing.GroupLayout(PanelImportMatriculas);
        PanelImportMatriculas.setLayout(PanelImportMatriculasLayout);
        PanelImportMatriculasLayout.setHorizontalGroup(
            PanelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportMatriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelImportMatriculasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textRutaMatriculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImportMatriculasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImportMatriculasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportarMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelImportMatriculasLayout.setVerticalGroup(
            PanelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportMatriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelImportMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRutaMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelImportacionesLayout = new javax.swing.GroupLayout(PanelImportaciones);
        PanelImportaciones.setLayout(PanelImportacionesLayout);
        PanelImportacionesLayout.setHorizontalGroup(
            PanelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelImportCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelImportAsignaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelImportMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelImportGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelImportAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelImportacionesLayout.setVerticalGroup(
            PanelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImportacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelImportCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelImportGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelImportacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelImportAsignaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelImportAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelImportMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        tabbedPage.addTab("Importaciones", PanelImportaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPage)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPage)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * Controlador del botón de Ayuda
     */
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        switch (tabbedPage.getSelectedIndex()) {
            case 0:
                //Ayuda de la pestaña general (opciones)
                break;
            case 1:
                //Ayuda de la pestaña Devoluciones (opciones)
                break;
            case 2:
                //Ayuda de la pestaña Entregas (opciones)
                break;
            case 3:
                //Ayuda de la pestaña Gestiones (opciones)
                break;
            case 4:
                //Ayuda de la pestaña Importaciones (opciones)
                break;
        }
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar las matriculas
     */
    private void btnImportarMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarMatriculasActionPerformed
        // TODO add your handling code here:

        if (!textRutaMatriculas.getText().equals("")) {
            try {
                new ImportarMatriculasXML(textRutaMatriculas.getText());

                JOptionPane.showMessageDialog(this, "Matrículas importadas correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar las matrículas.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar las matrículas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarMatriculasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de las matriculas
     */
    private void btnSeleccionMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionMatriculasActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaMatriculas.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionMatriculasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar los cursos
     */
    private void btnImportarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCursosActionPerformed
        // TODO add your handling code here:
        if (!textRutaCursos.getText().equals("")) {
            try {
                new ImportarCursoXML(textRutaCursos.getText());

                JOptionPane.showMessageDialog(this, "Cursos importados correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar los cursos.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar los cursos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarCursosActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de los cursos
     */
    private void btnSeleccionCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionCursosActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaCursos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionCursosActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de los grupos
     */
    private void btnSeleccionGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionGruposActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaGrupos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionGruposActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar los grupos
     */
    private void btnImportarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarGruposActionPerformed
        // TODO add your handling code here:
        if (!textRutaGrupos.getText().equals("")) {
            try {
                new ImportarGruposXML(textRutaGrupos.getText());

                JOptionPane.showMessageDialog(this, "Grupos importados correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar los grupos.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar los grupos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarGruposActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de las asignaturas
     */
    private void btnSeleccionAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionAsignaturasActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaContenidos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionAsignaturasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar las asignaturas
     */
    private void btnImportarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarAsignaturasActionPerformed
        // TODO add your handling code here:
        if (!textRutaContenidos.getText().equals("")) {
            try {
                new ImportarContenidoXML(textRutaContenidos.getText());

                JOptionPane.showMessageDialog(this, "Asignaturas importadas correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar las asignaturas.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar las asignaturas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarAsignaturasActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para seleccionar el archivo XML
     * de los alumnos
     */
    private void btnSeleccionAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionAlumnosActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "XML", "xml");

        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textRutaAlumnos.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSeleccionAlumnosActionPerformed

    /**
     *
     * (Pestaña Importaciones) Botón utilizado para importar los alumnos
     */
    private void btnImportarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarAlumnosActionPerformed
        // TODO add your handling code here:
        if (!textRutaAlumnos.getText().equals("")) {
            try {
                new ImportarAlumnosXML(textRutaAlumnos.getText());

                JOptionPane.showMessageDialog(this, "Alumnos importados correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se han podido importar los alumnos.\n-Revise el archivo XML.\nError: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un archivo para poder importar los alumnos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarAlumnosActionPerformed

    /**
     * Metodo para comprobar la conexión con el servidor de BD
     *
     * @param evt
     */
    private void btnComprobarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarRedActionPerformed
        // TODO add your handling code here:
        String ip = "", error = "";
        int puerto = -1;

        if (textIPServidor.getText().equals("")) {
            error += "- La IP del servidor no puede estar vacía.\n";
        }else{
            ip = textIPServidor.getText();
        }

        if (textPuertoServidor.getText().equals("")) {
            error += "- El puerto del servidor no puede estar vacío.\n";
        } else {
            try {
                puerto = Integer.parseInt(textPuertoServidor.getText());
            } catch (Exception e) {
                error += "- El puerto del servidor debe ser un valor númerico.\n";
            }
        }

        if (!error.equals("")) {
            new FramePopup("Revise los siguientes errores:\n" + error,
                    new ImageIcon(getClass().getResource("/Imagenes/icons/alert-black.png")), "Aceptar").setVisible(true);
        } else {
            try {
                if (ComprobarConexion.comprobarConexion(ip, puerto, "institut", "root", "")) {
                    new FramePopup("Conexión con el servidor correcta.",
                            new ImageIcon(getClass().getResource("/Imagenes/icons/check.png")), "Aceptar").setVisible(true);
                } else {
                    new FramePopup("No hay conexión con el servidor, revise la configuración.",
                            new ImageIcon(getClass().getResource("/Imagenes/icons/alert-black.png")), "Aceptar").setVisible(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
                new FramePopup("No hay conexión con el servidor, revise la configuración.",
                        new ImageIcon(getClass().getResource("/Imagenes/icons/alert-black.png")), "Aceptar").setVisible(true);
            }
        }
    }//GEN-LAST:event_btnComprobarRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelConfiguracionRed;
    private javax.swing.JPanel PanelDevoluciones;
    private javax.swing.JPanel PanelEntregas;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelGestiones;
    private javax.swing.JPanel PanelImportAlumnos;
    private javax.swing.JPanel PanelImportAsignaturas;
    private javax.swing.JPanel PanelImportCursos;
    private javax.swing.JPanel PanelImportGrupos;
    private javax.swing.JPanel PanelImportMatriculas;
    private javax.swing.JPanel PanelImportaciones;
    private com.mommoo.flat.button.FlatButton btnComprobarRed;
    private com.mommoo.flat.button.FlatButton btnHelp;
    private com.mommoo.flat.button.FlatButton btnImportarAlumnos;
    private com.mommoo.flat.button.FlatButton btnImportarAsignaturas;
    private com.mommoo.flat.button.FlatButton btnImportarCursos;
    private com.mommoo.flat.button.FlatButton btnImportarGrupos;
    private com.mommoo.flat.button.FlatButton btnImportarMatriculas;
    private com.mommoo.flat.button.FlatButton btnSeleccionAlumnos;
    private com.mommoo.flat.button.FlatButton btnSeleccionAsignaturas;
    private com.mommoo.flat.button.FlatButton btnSeleccionCursos;
    private com.mommoo.flat.button.FlatButton btnSeleccionGrupos;
    private com.mommoo.flat.button.FlatButton btnSeleccionMatriculas;
    private org.jdesktop.swingx.painter.GlossPainter glossPainter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane tabbedPage;
    private javax.swing.JTextField textIPServidor;
    private javax.swing.JTextField textPuertoServidor;
    private javax.swing.JTextField textRutaAlumnos;
    private javax.swing.JTextField textRutaContenidos;
    private javax.swing.JTextField textRutaCursos;
    private javax.swing.JTextField textRutaGrupos;
    private javax.swing.JTextField textRutaMatriculas;
    // End of variables declaration//GEN-END:variables
}
